spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/ysq_video?serverTimezone=Asia/Shanghai&characterEncoding=utf-8&useSSL=false
    username: root
    password: ysqJYKL2010
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      # 下面为连接池的补充设置，应用到上面所有数据源中
      # 初始化大小，最小，最大
      initial-size: 5
      min-idle: 5
      max-active: 20
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat,wall
      use-global-data-source-stat: true
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connect-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      # 配置监控服务器 http://127.0.0.1:8080/druid
      stat-view-servlet:
        # 1.1.10以后的版本需要指定为true 不然默认是关闭的就会出现404
        enabled: true
        login-username: admin
        login-password: 123456
        reset-enable: false
        url-pattern: /druid/*
        # 添加IP白名单
        #allow:
        # 添加IP黑名单，当白名单和黑名单重复时，黑名单优先级更高
        #deny:
      web-stat-filter:
        # 添加过滤规则
        url-pattern: /*
        # 忽略过滤格式
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
  redis:
    host: 119.45.164.115
    port: 6379
    password: ysqJYKL2010
    database: 0
    jedis:
      pool:
        max-active: 32  # 连接池连接的最大数量。-1表示没有限制
        max-wait: -1    # 连接池阻塞的最大的等待时间。-1表示一直等待
        max-idle: 20    # 连接池空闲连接的最大数量
        min-idle: 0     # 连接池空闲连接的最小数量
  servlet:
    multipart:
      enabled: true   # 默认为 true 即允许附件上传
      # 限定了当上传的文件超过定长度时，就先写到临时文件里
      # 这有助于上传文件不占用过多的内存，单位是 MB 或者。默认是 即不限定阔值
      file-size-threshold: 128KB
      # location 指的是临时文件的存放目录，如果不设定，则是服务器提供的一个临时目录
      location:
      max-file-size: 100MB  # 单个文件的最大长度，默认是 MB
      max-request-size: 125MB   # 单次 HTTP 请求上传的最大长度

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
#  type-aliases-package:
  configuration:
    map-underscore-to-camel-case: true  # 驼峰命名转换
    # 增加打印sql语句，一般用于本地开发测试
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
swagger:
  enabled: true
  title: "使用swagger2构建【畅意随拍】短视频后端的API接口文档"
  description: "欢迎访问【畅意随拍】短视频后端的API接口文档，这里是描述信息"
  version: "1.0"
  license: "Apache License, Version 2.0"
  licenseUrl: "https://www.apache.org/licenses/LICENSE-2.0.html"
  termsOfServiceUrl: "https://github.com/dyc87112/spring-boot-starter-swagger"
  contact:
    name: "passerbyYSQ"
    url: "https://blog.csdn.net/qq_43290318"
    email: "欢迎访问【畅意随拍】短视频后端的API接口文档，这里是描述信息"
  base-package: "net.ysq.video.controller"
  base-path: "/**"
  exclude-path: /error

